### ISSUE TITLE
Data structures implement Serde's `Serialize`, `Deserialize` (C-SERDE)

### ISSUE THREAD

**Issue by jfrimmel** [jfrimmel/partial-array#12]
This is part of the Rust API guidelines (#6).

This should be implemented as a new optional, disabled-by-default feature called `serde`. If that feature is implemented, a new module can be included, which implements `Serialize`/`Deserialize`, e.g.:
```rust
// lib.rs
#[cfg(feature = "serde")]
mod serde;
```
```toml
# Cargo.toml
[dependencies.serde]
version = "1.0"
optional = true
```
